import os
import sys
import pandas as pd
from datetime import datetime

# Add the current directory to the path so we can import config
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

try:
    import config
    from analyze_fast_protocol import load_data, calculate_metrics, generate_summary
except ImportError:
    try:
        from . import config
        from .analyze_fast_protocol import load_data, calculate_metrics, generate_summary
    except ImportError:
        import config
        from analyze_fast_protocol import load_data, calculate_metrics, generate_summary

def create_report(df, summary):
    """Generate a markdown report of the analysis."""
    report_path = os.path.join(config.OUTPUT_DIR, 'fast_protocol_analysis_report.md')
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Generate content
    content = f"""# Fast Protocol User Community Analysis Report
Date: {timestamp}

## Executive Summary
- **Total Unique Wallets:** {summary['total_unique_wallets']} (90 distinct addresses)
- **Total Claims/Participations:** {summary['total_claims']} (121 total entries)
- **Total Wallet Value:** ${summary.get('total_wallet_value', 0):,.2f}
- **Total Collections Tracked:** {summary['total_collections']}
- **Most Popular Collection:** {summary['top_collection']} ({summary['top_collection_wallets']} wallets)
- **Average Wallets per Collection:** {summary['avg_wallets_per_collection']:.2f}

## Collection Performance

### Top 10 Collections
| Rank | Collection | Unique Wallets | Category | Percentage |
|------|------------|----------------|----------|------------|
"""
    
    # Add top 10 table
    top_10 = df.head(10)
    for _, row in top_10.iterrows():
        content += f"| {row['rank']} | {row['entity']} | {row['unique_wallets']} | {row['category']} | {row['percentage']}% |\n"

    content += """
### Category Breakdown
"""
    # Add category breakdown
    for cat, count in summary['collections_by_category'].items():
        percent = (count / summary['total_claims'] * 100) if summary['total_claims'] > 0 else 0
        content += f"- **{cat}:** {count} wallets ({percent:.1f}%)\n"

    content += """
## Key Insights
1. **Top Performer:** The highest engagement comes from the **{}** collection.
2. **Category Dominance:** **{}** collections currently drive the most user activity.
3. **Engagement:** Total unique participation is **{}** wallets across all tracked campaigns.

## Appendix
- Data source: Fast Protocol API
- Generated by: Antigravity Analysis Pipeline
- Full data available in `fast_protocol_collections.csv`
""".format(
        summary['top_collection'],
        max(summary['collections_by_category'], key=summary['collections_by_category'].get),
        summary['total_claims']
    )

    with open(report_path, 'w') as f:
        f.write(content)
    
    print(f"Report generated at: {report_path}")
    return report_path  

if __name__ == "__main__":
    print("Generating report...")
    df = load_data()
    if df is not None:
        df = calculate_metrics(df)
        summary = generate_summary(df)
        create_report(df, summary)
